# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: Npm@1
  inputs:
    command: 'install'
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
- task: DotNetCoreCLI@2
  inputs:
   command: 'build'
   projects: 'Angular-Azure\Angular-Azure.csproj'
   
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build SourcesDirectory)'
    Contents: 'bin\Debug\netcoreapp3.1\**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
   
